language: clojure

install:
  # Install dependencies.
  - lein run

script:
  # Run unit tests and generate code coverage report.
  - lein cloverage

  # Build binary.
  - lein uberjar

  # Test that binary works.
  - java -jar target/raml2http.jar

  # TODO Run integration/acceptance tests

after_success:
  - echo Seems to work!


after_script:
  # Run various code quality tools. Just for information.
  - lein eastwood
  - lein kibit
  - lein bikeshed

  # Check for outdated project dependencies.
  - lein deps

  # Display all annotations
  - lein annotations

before_deploy:
  - if [ -n "$TRAVIS_TAG" ]; then
    # add version suffix if TAG
    mv target/raml2http.jar target/raml2http-${TRAVIS-TAG}.jar;
    else;
    # create temporary tag for deploy so that release from master
    # would not be named untagged-....
    git tag latest
    fi

# Deploy jar file to Github releases
deploy:
  # master branch updates 'latest'
  - provider: releases
    api_key: $GITHUB_TOKEN
    name: latest ($(date +'%d.%m.%Y %R'))
    file: target/raml2http.jar
    skip_cleanup: true
    overwrite: true
    on:
      branch: feature/publish_jar
  # tags have unique releases
  # todo add body w/ release notes?
  - provider: releases
    api_key: $GITHUB_TOKEN
    body: "https://github.com/PlatformOfTrust/code-examples-generator/blob/master/CHANGELOG.md"
    file: target/raml2http-${TRAVIS-TAG}.jar
    skip_cleanup: true
    tags: true

