language: clojure

install:
  # Install dependencies.
  - lein run

script:
  # Run unit tests and generate code coverage report.
  - lein cloverage

  # Build binary.
  - lein uberjar

  # Test that binary works.
  - java -jar target/raml2http.jar

  # TODO Run integration/acceptance tests

after_success:
  - echo Seems to work!


after_script:
  # Run various code quality tools. Just for information.
  - lein eastwood
  - lein kibit
  - lein bikeshed

  # Check for outdated project dependencies.
  - lein deps

  # Display all annotations
  - lein annotations

before_deploy:
  # upload jar file to docs folder so that it will be
  # published to github pages and can be download with cURL
  - mkdir ./docs
  - if [ -n "$TRAVIS_TAG" ]; then 
    mv target/raml2http.jar target/raml2http-${TRAVIS-TAG}.jar;
    fi

# Deploy jar file to Github releases
deploy:
  # drafts from master branch
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: target/raml2http.jar
    skip_cleanup: true
    draft: true
    on:
      branch: feature/publish_jar
  # releaseses from tags
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: target/raml2http-${TRAVIS-TAG}.jar
    skip_cleanup: true
    on:
      tags: true

