language: clojure

env:
  global:
    # Folder for generated code examples. Used for e2e tests
    - CODE_EXAMPLES=$TRAVIS_BUILD_DIR/code-examples
    # Location of RAML files for testing
    - RAML_FILES=$TRAVIS_BUILD_DIR/test-resources/raml
    # Scheme for e2e tests
    - SCHEME=http
    # Host for e2e tests
    - HOST=mockbin.org/request

before_install:
  # nodejs for e2e tests
  - sudo apt-get install nodejs npm
  
install:
  # Install dependencies.
  - lein run

script:
  # Run unit tests and generate code coverage report.
  - lein cloverage

  # Build binary.
  - lein uberjar

  # Show version, make sure that the binary works.
  - java -jar $TRAVIS_BUILD_DIR/target/raml2http.jar --version

  # TODO Run integration/acceptance tests

  # Run e2e tests
  - ./scripts/generate_examples.sh
  - ./scripts/e2e_tests/nodejs.sh
  - ./scripts/e2e_tests/python.sh
  - ./scripts/e2e_tests/curl.sh

before_deploy:
  # add version suffix if TAG or create temporary local tag for deployment
  # so that release from master would not be named untagged-...
  # https://docs.travis-ci.com/user/deployment/releases/#setting-the-tag-at-deployment-time
  - if [ -n "$TRAVIS_TAG" ]; then
      mv target/raml2http.jar target/raml2http-${TRAVIS_TAG}.jar;
    else
      export TRAVIS_TAG=latest;
    fi

# Deploy jar file to Github releases
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    name: latest ($(date +'%Y-%m-%d'))
    tag_name: $TRAVIS_TAG
    target_commitish: $TRAVIS_COMMIT
    body: "Binary built from latest commit to master branch ($TRAVIS_COMMIT).</br></br>```$TRAVIS_COMMIT_MESSAGE```"
    file: target/raml2http.jar
    overwrite: true
    skip_cleanup: true
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    body: "<a href=\"./CHANGELOG.md\">Change log</a>"
    file: target/raml2http-${TRAVIS_TAG}.jar
    overwrite: true
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_TAG != latest"
      
after_script:
  # Run various code quality tools. Just for information.
  - lein eastwood
  - lein kibit
  - lein bikeshed

  # Check for outdated project dependencies.
  - lein deps

  # Display all annotations
  - lein annotations
